# To run the linter locally install it from https://golangci-lint.run/usage/install/
# Running `golangci-lint run` in the root of this repo will pickup this config file
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - loggercheck
    - goconst
    - gofmt
    - goimports
    - revive
  disable:
    - golint
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
       -  errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true
linters-settings:
  revive:
    rules:
      - name: blank-imports
        severity: warning
        exclude: [""]
        disable: false
      - name: exported
        severity: warning
        disabled: false
        exclude: [""]
